// The todocli session objects this service parses (PLAN §3.12, §7.6):
// test/fixtures/contract/pomodoro-*.json hold what the real binary prints for
// `pomodoro start|done|cancel|interrupt|retarget`, generated by todocli's
// tests/contract.rs and vendored here byte for byte, pinned by SHA-256 the
// way test/loader.test.mjs pins the shared loader. todocli's contract test
// reads this directory back and fails when a copy differs from its golden.
// Re-vendoring: copy the goldens over, then paste the pins this test prints
// on a mismatch.
import { test } from "node:test"
import assert from "node:assert/strict"
import { createHash } from "node:crypto"
import fs from "node:fs"
import path from "node:path"
import { loadQmlJs } from "./qml-js-loader.mjs"

const T = loadQmlJs(new URL("../Timer.js", import.meta.url).pathname)
const dir = new URL("./fixtures/contract/", import.meta.url).pathname

const PINS = {
  "pomodoro-cancel.json": "b5d24c6483c975eac046dcdf9451c6358869109c4f2a7161dedda5ae4ff0ee3d",
  "pomodoro-done.json": "383a813b3989f6129109e7510fe73fc7503f8eb347fd6224e10d52cf7538a3a7",
  "pomodoro-interrupt.json": "b7dcfcbbf95a23ee59bdb561e26967181d9ffc9c2b715f728ff8130a5cea68db",
  "pomodoro-retarget.json": "26a560cea71bc863a2d2a0e56cb407a1924bde3a94ae7804d8e186aefa87ad99",
  "pomodoro-start.json": "a553305b029ad90ee0b1903e5b2bcd9d9e886f519032b0510a35772e1a7989c2",
}

const bytes = (name) => fs.readFileSync(path.join(dir, name))
const sha = (name) => createHash("sha256").update(bytes(name)).digest("hex")

test("every vendored session golden is pinned, every pin has its golden, and the bytes match", () => {
  const files = fs.readdirSync(dir).filter((f) => f.endsWith(".json")).sort()
  assert.deepEqual(files, Object.keys(PINS).sort(), "the vendored set and the pin table name the same files")
  const drift = files.filter((f) => sha(f) !== PINS[f])
  assert.deepEqual(drift, [], "re-vendored goldens; new pins:\n" + files.map((f) => `  "${f}": "${sha(f)}",`).join("\n"))
})

test("the goldens are session objects parseSession accepts: a uid, the task, the outcome of every verb", () => {
  const outcome = { start: "running", done: "completed", cancel: "abandoned", interrupt: "interrupted", retarget: "running" }
  for (const [verb, want] of Object.entries(outcome)) {
    const session = T.parseSession(bytes(`pomodoro-${verb}.json`).toString("utf8"))
    assert.ok(session, `${verb}: parseSession accepts the golden`)
    assert.equal(session.uid, "$UID", `${verb}: the uid is the run's, normalised by the generator`)
    assert.equal(session.outcome, want, `${verb}: outcome`)
    assert.equal(session.planned_seconds, verb === "retarget" ? 900 : 1500, `${verb}: planned seconds`)
    assert.equal(session.ended_at === null, want === "running", `${verb}: ended_at is null while running`)
  }
  const done = T.parseSession(bytes("pomodoro-done.json").toString("utf8"))
  assert.deepEqual([done.task_id, done.label, done.focus_seconds], [3, "Wire the webhook", 0])
  const retarget = T.parseSession(bytes("pomodoro-retarget.json").toString("utf8"))
  assert.deepEqual([retarget.task_id, retarget.label], [null, "Elsewhere"], "a label-only retarget has no task")
})
