// Transitions and replies of the pomodoro machine (PLAN §7.3, A47; UX §6.2,
// A53; AC-6.12, 6.13, 6.15, 6.18): what `startFor`, `toggle`, `pause`,
// `resume`, `skip`, `reset` and `detach` answer and do to the phase, the
// deadline and the focus seconds; how a tick accrues time, checkpoints and
// detects a suspend; the break cycle. Driven through Timer.js, the assembled
// machine Service.qml dispatches into, with every record answered by a fresh
// fake session.
import { test } from "node:test"
import assert from "node:assert/strict"
import { loadQmlJs } from "./qml-js-loader.mjs"
import { Sim, fakeSessions, startFor } from "./harness.mjs"

const T = loadQmlJs(new URL("../Timer.js", import.meta.url).pathname)
const CLI = T.settings({ backend: "cli" })
const fake = fakeSessions()
const newSim = (cfg, now) => new Sim(T, cfg, { now, answer: fake.ok })

// ------------------------------------------------------ startFor (UX 6.2)

test("startFor: idle attaches and starts work; the record is start --interrupt", () => {
  const sim = newSim(CLI)
  assert.equal(startFor(sim, "3", "Wire the payment-provider webhook"), "started")
  assert.equal(sim.state.phase, "work")
  assert.equal(sim.state.running, true)
  assert.equal(sim.state.remaining, 1500)
  assert.equal(sim.state.endsAt, 1500000)
  assert.equal(sim.state.taskId, "3")
  assert.equal(sim.state.taskLabel, "Wire the payment-provider webhook")
  const r = sim.records()
  assert.equal(r.length, 1)
  assert.equal(r[0].verb, "start")
  assert.equal(r[0].taskId, "3")
  assert.equal(r[0].planned, 1500)
  assert.equal(r[0].interrupt, true)
  assert.equal(r[0].startedAt, null)
  assert.equal(sim.state.sessionUid, fake.last)
  assert.equal(sim.writes().length >= 1, true)
})

test("startFor: empty label is refused without a change", () => {
  const sim = newSim(CLI)
  assert.equal(startFor(sim, "3", "  \n "), "empty")
  assert.equal(sim.state.phase, "idle")
  assert.equal(sim.records().length, 0)
})

test("startFor: same task while running is already running; different task retargets (AC-6.13)", () => {
  const sim = newSim(CLI)
  startFor(sim, "3", "Wire it")
  sim.tick(300)
  sim.clear()
  const first = sim.state.sessionUid
  assert.equal(startFor(sim, "3", "Wire it"), "already running")
  assert.equal(sim.records().length, 0)
  assert.equal(startFor(sim, "8", "Book dentist"), "retargeted")
  assert.equal(sim.state.remaining, 1200)
  assert.equal(sim.state.taskId, "8")
  assert.equal(sim.state.taskLabel, "Book dentist")
  assert.equal(sim.state.running, true)
  const r = sim.records()
  assert.equal(r.length, 1)
  assert.equal(r[0].verb, "retarget")
  assert.equal(r[0].focusSeconds, 300)
  assert.equal(r[0].taskId, "8")
  assert.equal(r[0].planned, 1200)
  assert.equal(r[0].sessionUid, first)
  const second = sim.state.sessionUid
  assert.notEqual(second, first)
  assert.equal(sim.state.focusSeconds, 0)
  sim.tick(1200)
  const done = sim.records().find((e) => e.verb === "done")
  assert.equal(done.sessionUid, second)
  assert.equal(done.focusSeconds, 1200)
})

test("startFor: no task id while running retargets the label; the same label is left alone", () => {
  const sim = newSim(CLI)
  startFor(sim, "", "Admin")
  assert.equal(sim.records()[0].taskId, "")
  assert.equal(sim.records()[0].label, "Admin")
  sim.tick(10)
  sim.clear()
  assert.equal(startFor(sim, "", "Admin"), "already running")
  assert.equal(startFor(sim, "", "Email"), "retargeted")
  assert.equal(sim.records()[0].verb, "retarget")
  assert.equal(sim.records()[0].label, "Email")
  assert.equal(sim.records()[0].taskId, "")
})

test("startFor: paused work resumes for the same task and retargets + resumes for another", () => {
  const sim = newSim(CLI)
  startFor(sim, "3", "Wire it")
  sim.tick(100)
  sim.apply({ type: "pause" })
  assert.equal(sim.state.running, false)
  sim.clear()
  assert.equal(startFor(sim, "3", "Wire it"), "resumed")
  assert.equal(sim.state.running, true)
  assert.equal(sim.records().length, 0)
  sim.apply({ type: "pause" })
  sim.clear()
  assert.equal(startFor(sim, "9", "Other"), "retargeted")
  assert.equal(sim.state.running, true)
  assert.equal(sim.state.remaining, 1400)
  assert.equal(sim.verbs()[0], "retarget")
})

test("startFor: during a break ends the break and starts work, count unchanged", () => {
  const sim = newSim(CLI)
  startFor(sim, "3", "Wire it")
  sim.tick(1500)
  assert.equal(sim.state.phase, "shortBreak")
  assert.equal(sim.state.completed, 1)
  sim.tick(30)
  sim.clear()
  assert.equal(startFor(sim, "4", "Next"), "started")
  assert.equal(sim.state.phase, "work")
  assert.equal(sim.state.running, true)
  assert.equal(sim.state.completed, 1)
  assert.equal(sim.state.remaining, 1500)
  assert.deepEqual(sim.verbs(), ["start"])
  assert.equal(sim.records()[0].taskId, "4")
})

test("startFor: a non-numeric task id is kept on the timer but recorded by label", () => {
  const sim = newSim(CLI)
  assert.equal(startFor(sim, "t1abc", "Json item"), "started")
  assert.equal(sim.state.taskId, "t1abc")
  const argv = T.recordArgv("todocli", sim.records()[0])
  assert.equal(argv.indexOf("t1abc"), -1)
  assert.equal(argv.indexOf("--label=Json item") > 0, true)
})

// ------------------------------------------------ transport replies (A53)

test("start/pause/resume/reset/skip/detach replies and effects", () => {
  const sim = newSim(CLI)
  assert.equal(sim.apply({ type: "pause" }), "idle")
  assert.equal(sim.apply({ type: "detach" }), "idle")
  assert.equal(sim.apply({ type: "resume" }), "idle")
  assert.equal(sim.apply({ type: "skip" }), "ok")
  assert.equal(sim.apply({ type: "reset" }), "ok")
  assert.equal(sim.state.phase, "idle")
  assert.equal(sim.records().length, 0)
  assert.equal(sim.apply({ type: "toggle" }), "started")
  assert.equal(sim.state.phase, "work")
  assert.equal(sim.records()[0].taskId, "")
  assert.equal(sim.records()[0].label, "")
  assert.equal(T.recordArgv("todocli", sim.records()[0]).indexOf("--label=Pomodoro") > 0, true)
  sim.tick(10)
  assert.equal(sim.apply({ type: "toggle" }), "paused")
  assert.equal(sim.state.running, false)
  assert.equal(sim.state.endsAt, null)
  assert.equal(sim.apply({ type: "toggle" }), "resumed")
  assert.equal(sim.state.endsAt, sim.now + 1490 * 1000)
  assert.equal(sim.apply({ type: "pause" }), "paused")
  assert.equal(sim.apply({ type: "pause" }), "resumed")
  assert.equal(sim.apply({ type: "resume" }), "resumed")
  assert.equal(sim.apply({ type: "pause" }), "paused")
  assert.equal(sim.apply({ type: "resume" }), "resumed")
  sim.tick(5)
  assert.equal(sim.apply({ type: "reset" }), "ok")
  assert.equal(sim.state.remaining, 1500)
  assert.equal(sim.state.running, false)
  assert.equal(sim.state.focusSeconds, 15)
  assert.equal(sim.apply({ type: "detach" }), "detached")
  sim.clear()
  assert.equal(sim.apply({ type: "skip" }), "ok")
  assert.equal(sim.state.phase, "shortBreak")
  assert.equal(sim.state.running, true)
  assert.equal(sim.state.completed, 0)
  assert.equal(sim.apply({ type: "skip" }), "ok")
  assert.equal(sim.state.phase, "work")
  assert.equal(sim.state.running, false)
  assert.equal(sim.apply({ type: "detach" }), "detached")
})

test("reset while running pauses at the full phase length; a session keeps its seconds", () => {
  const sim = newSim(CLI)
  startFor(sim, "3", "Wire it")
  sim.tick(100)
  sim.clear()
  sim.apply({ type: "reset" })
  assert.equal(sim.state.remaining, 1500)
  assert.equal(sim.state.running, false)
  assert.equal(sim.records().length, 0)
  sim.apply({ type: "resume" })
  sim.tick(1500)
  const done = sim.records().find((e) => e.verb === "done")
  assert.equal(done.focusSeconds, 1600)
})

test("detach during a break clears the label without a record and without focus time", () => {
  const sim = newSim(CLI)
  startFor(sim, "3", "Wire…")
  sim.tick(1500)
  sim.clear()
  sim.now += 1500
  assert.equal(sim.apply({ type: "detach" }), "detached")
  assert.equal(sim.records().length, 0)
  assert.equal(sim.state.taskLabel, "")
  assert.equal(sim.state.focusSeconds, 0)
  assert.equal(sim.state.running, true)
})

// ---------------------------------------- ticks, focus time and the cycle

// 1500 s of work around a 600 s pause completes at AC-6.12's 2100 s.
test("AC-6.12 pauses are excluded from focus seconds", () => {
  const sim = newSim(CLI)
  startFor(sim, "3", "Wire…")
  sim.tick(600)
  sim.apply({ type: "pause" })
  sim.tick(600)
  assert.equal(sim.state.phase, "work")
  assert.equal(sim.state.remaining, 900)
  sim.apply({ type: "resume" })
  sim.tick(900)
  assert.equal(sim.now, 2100000)
  assert.equal(sim.state.phase, "shortBreak")
  assert.equal(sim.records().find((e) => e.verb === "done").focusSeconds, 1500)
})

test("AC-6.15 suspend pauses; it never completes", () => {
  const sim = newSim(CLI)
  startFor(sim, "3", "Wire…")
  sim.tick(300)
  assert.equal(sim.state.remaining, 1200)
  sim.clear()
  sim.now = 3900000
  sim.apply({ type: "tick" })
  assert.equal(sim.state.running, false)
  assert.equal(sim.state.phase, "work")
  assert.equal(Math.abs(sim.state.remaining - 1200) <= 1, true)
  assert.equal(sim.state.focusSeconds, 300)
  assert.equal(sim.records().length, 0)
  assert.equal(sim.writes().length, 1)
  assert.equal(sim.state.endsAt, null)
  sim.apply({ type: "resume" })
  sim.tick(1200)
  assert.equal(sim.state.phase, "shortBreak")
  assert.equal(sim.records().find((e) => e.verb === "done").focusSeconds, 1500)
})

test("AC-6.18 the state file is checkpointed at most once a minute while running", () => {
  const sim = newSim(CLI)
  startFor(sim, "3", "Wire…")
  sim.clear()
  sim.tick(150)
  const w = sim.writes()
  assert.deepEqual(w.map((e) => e.doc.updatedAt), [60000, 120000])
  assert.deepEqual(w.map((e) => e.doc.focusSeconds), [60, 120])
  sim.clear()
  sim.apply({ type: "pause" })
  assert.equal(sim.writes().length, 1)
  assert.equal(sim.writes()[0].doc.focusSeconds, 150)
  assert.equal(sim.writes()[0].doc.running, false)
  sim.clear()
  sim.tick(200)
  assert.equal(sim.writes().length, 0)
})

test("tick while idle or paused changes nothing", () => {
  const sim = newSim(CLI)
  sim.tick(5)
  assert.equal(sim.state.phase, "idle")
  assert.equal(sim.effects.length, 0)
  startFor(sim, "3", "Wire…")
  sim.apply({ type: "pause" })
  sim.clear()
  sim.tick(5)
  assert.equal(sim.effects.length, 0)
  assert.equal(sim.state.focusSeconds, 0)
})

test("focus seconds add min(2, Δt) per tick; break time is not focus time", () => {
  const sim = newSim(CLI)
  startFor(sim, "3", "Wire…")
  sim.now += 4000
  sim.apply({ type: "tick" })
  assert.equal(sim.state.focusSeconds, 2)
  assert.equal(sim.state.remaining, 1496)
  sim.now += 1500
  sim.apply({ type: "tick" })
  assert.equal(sim.state.focusSeconds, 3.5)
  sim.apply({ type: "skip" })
  assert.equal(sim.records().at(-1).focusSeconds, 4)
  sim.tick(10)
  assert.equal(sim.state.focusSeconds, 0)
})

test("long break after pomodorosPerCycle; the count resets after it", () => {
  const sim = newSim(T.settings({ backend: "cli", pomodorosPerCycle: 2, workMinutes: 1, shortBreakMinutes: 1, longBreakMinutes: 2 }))
  sim.apply({ type: "toggle" })
  sim.tick(60)
  assert.equal(sim.state.phase, "shortBreak")
  assert.equal(sim.state.completed, 1)
  sim.tick(60)
  assert.equal(sim.state.phase, "work")
  assert.equal(sim.state.running, false)
  sim.apply({ type: "toggle" })
  sim.tick(60)
  assert.equal(sim.state.phase, "longBreak")
  assert.equal(sim.state.completed, 2)
  assert.equal(sim.state.remaining, 120)
  assert.equal(sim.notifies().at(-1).argv[6], "Long break — you earned it.")
  sim.tick(120)
  assert.equal(sim.state.phase, "work")
  assert.equal(sim.state.completed, 0)
})

test("sound effects are omitted when sound is off", () => {
  const sim = newSim(T.settings({ sound: "false", workMinutes: 1 }))
  sim.apply({ type: "toggle" })
  sim.tick(60)
  assert.equal(sim.notifies().length, 1)
  assert.equal(sim.sounds().length, 0)
})

test("unknown events are ignored, including prototype keys and a missing event", () => {
  const sim = newSim(CLI)
  assert.equal(sim.apply({ type: "bogus" }), "")
  assert.equal(sim.apply({}), "")
  assert.equal(sim.apply({ type: "toString" }), "")
  assert.equal(sim.apply({ type: "hasOwnProperty" }), "")
  assert.equal(sim.apply(null), "")
  assert.equal(sim.apply(undefined), "")
  assert.equal(sim.effects.length, 0)
  sim.apply({ type: "recordResult", id: 99, exitCode: 0, exitStatus: 0, stdout: "", stderr: "" })
  assert.equal(sim.state.lastRecordError, null)
})
