// Transitions and replies of the pomodoro machine (PLAN §7.3, A47; UX §6.2,
// A53; AC-6.12, 6.13, 6.15, 6.18): what `startFor`, `toggle`, `pause`,
// `resume`, `skip`, `reset` and `detach` answer and do to the phase, the
// deadline and the focus seconds; how a tick accrues time, checkpoints and
// detects a suspend; the break cycle. Driven through Timer.js, the assembled
// machine Service.qml dispatches into, with every record answered by a fresh
// fake session.
import { test } from "node:test"
import assert from "node:assert/strict"
import { loadQmlJs } from "./qml-js-loader.mjs"
import { Sim, fakeSessions, startFor } from "./harness.mjs"

const T = loadQmlJs(new URL("../Timer.js", import.meta.url).pathname)
const CLI = T.settings({ backend: "cli" })
const fake = fakeSessions()
const newSim = (cfg, now) => new Sim(T, cfg, { now, answer: fake.ok })

// ------------------------------------------------------ startFor (UX 6.2)

test("startFor: idle attaches and starts work; the record is start --interrupt", () => {
  const sim = newSim(CLI)
  assert.equal(startFor(sim, "3", "Wire the payment-provider webhook"), "started")
  assert.equal(sim.state.phase, "work")
  assert.equal(sim.state.running, true)
  assert.equal(sim.state.remaining, 1500)
  assert.equal(sim.state.endsAt, 1500000)
  assert.equal(sim.state.taskId, "3")
  assert.equal(sim.state.taskLabel, "Wire the payment-provider webhook")
  const r = sim.records()
  assert.equal(r.length, 1)
  assert.equal(r[0].verb, "start")
  assert.equal(r[0].taskId, "3")
  assert.equal(r[0].planned, 1500)
  assert.equal(r[0].interrupt, true)
  assert.equal(r[0].startedAt, null)
  assert.equal(sim.state.sessionUid, fake.last)
  assert.equal(sim.writes().length >= 1, true)
})

test("startFor: empty label is refused without a change", () => {
  const sim = newSim(CLI)
  assert.equal(startFor(sim, "3", "  \n "), "empty")
  assert.equal(sim.state.phase, "idle")
  assert.equal(sim.records().length, 0)
})

test("startFor: same task while running is already running; different task retargets (AC-6.13)", () => {
  const sim = newSim(CLI)
  startFor(sim, "3", "Wire it")
  sim.tick(300)
  sim.clear()
  const first = sim.state.sessionUid
  assert.equal(startFor(sim, "3", "Wire it"), "already running")
  assert.equal(sim.records().length, 0)
  assert.equal(startFor(sim, "8", "Book dentist"), "retargeted")
  assert.equal(sim.state.remaining, 1200)
  assert.equal(sim.state.taskId, "8")
  assert.equal(sim.state.taskLabel, "Book dentist")
  assert.equal(sim.state.running, true)
  const r = sim.records()
  assert.equal(r.length, 1)
  assert.equal(r[0].verb, "retarget")
  assert.equal(r[0].focusSeconds, 300)
  assert.equal(r[0].taskId, "8")
  assert.equal(r[0].planned, 1200)
  assert.equal(r[0].sessionUid, first)
  const second = sim.state.sessionUid
  assert.notEqual(second, first)
  assert.equal(sim.state.focusSeconds, 0)
  sim.tick(1200)
  const done = sim.records().find((e) => e.verb === "done")
  assert.equal(done.sessionUid, second)
  assert.equal(done.focusSeconds, 1200)
})

test("startFor: no task id while running retargets the label; the same label is left alone", () => {
  const sim = newSim(CLI)
  startFor(sim, "", "Admin")
  assert.equal(sim.records()[0].taskId, "")
  assert.equal(sim.records()[0].label, "Admin")
  sim.tick(10)
  sim.clear()
  assert.equal(startFor(sim, "", "Admin"), "already running")
  assert.equal(startFor(sim, "", "Email"), "retargeted")
  assert.equal(sim.records()[0].verb, "retarget")
  assert.equal(sim.records()[0].label, "Email")
  assert.equal(sim.records()[0].taskId, "")
})

test("startFor: paused work resumes for the same task and retargets + resumes for another", () => {
  const sim = newSim(CLI)
  startFor(sim, "3", "Wire it")
  sim.tick(100)
  sim.apply({ type: "pause" })
  assert.equal(sim.state.running, false)
  sim.clear()
  assert.equal(startFor(sim, "3", "Wire it"), "resumed")
  assert.equal(sim.state.running, true)
  assert.equal(sim.records().length, 0)
  sim.apply({ type: "pause" })
  sim.clear()
  assert.equal(startFor(sim, "9", "Other"), "retargeted")
  assert.equal(sim.state.running, true)
  assert.equal(sim.state.remaining, 1400)
  assert.equal(sim.verbs()[0], "retarget")
})

test("startFor: during a break ends the break and starts work, count unchanged", () => {
  const sim = newSim(CLI)
  startFor(sim, "3", "Wire it")
  sim.tick(1500)
  assert.equal(sim.state.phase, "shortBreak")
  assert.equal(sim.state.completed, 1)
  sim.tick(30)
  sim.clear()
  assert.equal(startFor(sim, "4", "Next"), "started")
  assert.equal(sim.state.phase, "work")
  assert.equal(sim.state.running, true)
  assert.equal(sim.state.completed, 1)
  assert.equal(sim.state.remaining, 1500)
  assert.deepEqual(sim.verbs(), ["start"])
  assert.equal(sim.records()[0].taskId, "4")
})

test("startFor: a non-numeric task id is kept on the timer but recorded by label", () => {
  const sim = newSim(CLI)
  assert.equal(startFor(sim, "t1abc", "Json item"), "started")
  assert.equal(sim.state.taskId, "t1abc")
  const argv = T.recordArgv("todocli", sim.records()[0])
  assert.equal(argv.indexOf("t1abc"), -1)
  assert.equal(argv.indexOf("--label=Json item") > 0, true)
})

// ------------------------------------------------ transport replies (A53)

test("start/pause/resume/skip/detach replies and effects", () => {
  const sim = newSim(CLI)
  assert.equal(sim.apply({ type: "pause" }), "idle")
  assert.equal(sim.apply({ type: "detach" }), "idle")
  assert.equal(sim.apply({ type: "resume" }), "idle")
  assert.equal(sim.apply({ type: "skip" }), "ok")
  assert.equal(sim.apply({ type: "reset" }), "idle")
  assert.equal(sim.state.phase, "idle")
  assert.equal(sim.records().length, 0)
  assert.equal(sim.apply({ type: "toggle" }), "started")
  assert.equal(sim.state.phase, "work")
  assert.equal(sim.records()[0].taskId, "")
  assert.equal(sim.records()[0].label, "")
  assert.equal(T.recordArgv("todocli", sim.records()[0]).indexOf("--label=Pomodoro") > 0, true)
  sim.tick(10)
  assert.equal(sim.apply({ type: "toggle" }), "paused")
  assert.equal(sim.state.running, false)
  assert.equal(sim.state.endsAt, null)
  assert.equal(sim.apply({ type: "toggle" }), "resumed")
  assert.equal(sim.state.endsAt, sim.now + 1490 * 1000)
  assert.equal(sim.apply({ type: "pause" }), "paused")
  assert.equal(sim.apply({ type: "pause" }), "resumed")
  assert.equal(sim.apply({ type: "resume" }), "resumed")
  assert.equal(sim.apply({ type: "pause" }), "paused")
  assert.equal(sim.apply({ type: "resume" }), "resumed")
  sim.tick(5)
  assert.equal(sim.state.remaining, 1485)
  assert.equal(sim.state.focusSeconds, 15)
  assert.equal(sim.apply({ type: "detach" }), "detached")
  sim.clear()
  assert.equal(sim.apply({ type: "skip" }), "ok")
  assert.equal(sim.state.phase, "shortBreak")
  assert.equal(sim.state.running, true)
  assert.equal(sim.state.completed, 0)
  assert.equal(sim.apply({ type: "skip" }), "ok")
  assert.equal(sim.state.phase, "work")
  assert.equal(sim.state.running, false)
  assert.equal(sim.apply({ type: "detach" }), "detached")
})

// ------------------------------------------------ reset (UX 6.2, fork)

// Reset abandons the phase from wherever it is: idle, no task, no session,
// the state file written idle (so the pill shows the idle glyph and the todo
// panel's markers disappear). A recorded work session is cancelled with its
// running seconds through the skip path; a break or an unrecorded work
// phase records nothing. The count and a pending close are kept.
function assertIdleAfterReset(sim, completed) {
  const s = sim.state
  assert.equal(s.phase, "idle")
  assert.equal(s.running, false)
  assert.equal(s.endsAt, null)
  assert.equal(s.remaining, 0)
  assert.equal(s.taskId, "")
  assert.equal(s.taskLabel, "")
  assert.equal(s.sessionUid, null)
  assert.equal(s.focusSeconds, 0)
  assert.equal(s.recorded, false)
  assert.equal(s.restored, false)
  assert.equal(s.completed, completed)
  const w = sim.writes()
  assert.equal(w.length >= 1, true)
  for (const e of w) {
    assert.equal(e.doc.phase, "idle")
    assert.equal(e.doc.running, false)
    assert.equal(e.doc.taskId, "")
    assert.equal(e.doc.taskLabel, "")
    assert.equal(e.doc.sessionUid, null)
    assert.equal(e.doc.focusSeconds, 0)
  }
  const v = T.view(s, sim.cfg)
  assert.equal(v.hasSession, false)
  assert.equal(v.phaseGlyph, "")
  assert.equal(v.tooltip, "Pomodoro — click to start")
  assert.equal(v.attached, false)
}

test("reset while idle replies idle and changes nothing", () => {
  const sim = newSim(CLI)
  assert.equal(sim.apply({ type: "reset" }), "idle")
  assert.equal(sim.effects.length, 0)
  assert.deepEqual(sim.state, T.initialState())
})

test("reset from running work with a task cancels the session with its seconds and goes idle", () => {
  const sim = newSim(CLI)
  startFor(sim, "3", "Wire it")
  const uid = sim.state.sessionUid
  sim.tick(300)
  sim.clear()
  assert.equal(sim.apply({ type: "reset" }), "reset")
  const r = sim.records()
  assert.equal(r.length, 1)
  assert.equal(r[0].verb, "cancel")
  assert.equal(r[0].sessionUid, uid)
  assert.equal(r[0].focusSeconds, 300)
  assertIdleAfterReset(sim, 0)
  assert.equal(sim.notifies().length, 0)
  // Idle is a real idle: ticks do nothing, the next start is a fresh phase.
  sim.clear()
  sim.tick(5)
  assert.equal(sim.effects.length, 0)
  assert.equal(sim.apply({ type: "toggle" }), "started")
  assert.equal(sim.state.remaining, 1500)
  assert.equal(sim.state.taskLabel, "")
  assert.equal(sim.records()[0].verb, "start")
  assert.equal(sim.records()[0].taskId, "")
})

test("reset from paused work with a task cancels with the seconds before the pause", () => {
  const sim = newSim(CLI)
  startFor(sim, "3", "Wire it")
  const uid = sim.state.sessionUid
  sim.tick(100)
  sim.apply({ type: "pause" })
  sim.now += 50000
  sim.clear()
  assert.equal(sim.apply({ type: "reset" }), "reset")
  assert.deepEqual(sim.verbs(), ["cancel"])
  assert.equal(sim.records()[0].sessionUid, uid)
  assert.equal(sim.records()[0].focusSeconds, 100)
  assertIdleAfterReset(sim, 0)
  assert.equal(startFor(sim, "4", "Next"), "started")
})

test("reset from work without a task cancels the unlinked session; an unrecorded work phase records nothing", () => {
  const sim = newSim(CLI)
  sim.apply({ type: "toggle" })
  const uid = sim.state.sessionUid
  sim.tick(10)
  sim.clear()
  assert.equal(sim.apply({ type: "reset" }), "reset")
  assert.deepEqual(sim.verbs(), ["cancel"])
  assert.equal(sim.records()[0].sessionUid, uid)
  assert.equal(sim.records()[0].focusSeconds, 10)
  assertIdleAfterReset(sim, 0)
  // A break skipped into a paused work phase opened no session: nothing to cancel.
  const sim2 = newSim(CLI)
  startFor(sim2, "3", "Wire it")
  sim2.tick(1500)
  sim2.apply({ type: "skip" })
  assert.equal(sim2.state.phase, "work")
  assert.equal(sim2.state.recorded, false)
  sim2.clear()
  assert.equal(sim2.apply({ type: "reset" }), "reset")
  assert.equal(sim2.records().length, 0)
  assertIdleAfterReset(sim2, 1)
})

test("reset from a short break records nothing, drops the task and keeps the count", () => {
  const sim = newSim(CLI)
  startFor(sim, "3", "Wire it")
  sim.tick(1500)
  assert.equal(sim.state.phase, "shortBreak")
  sim.tick(30)
  sim.clear()
  assert.equal(sim.apply({ type: "reset" }), "reset")
  assert.equal(sim.records().length, 0)
  assertIdleAfterReset(sim, 1)
  // The same paused, and without a task.
  const sim2 = newSim(CLI)
  sim2.apply({ type: "toggle" })
  sim2.tick(1500)
  sim2.apply({ type: "pause" })
  sim2.clear()
  assert.equal(sim2.apply({ type: "reset" }), "reset")
  assert.equal(sim2.records().length, 0)
  assertIdleAfterReset(sim2, 1)
})

test("reset from a long break, with and without a task, records nothing and keeps the count", () => {
  const cfg = T.settings({ backend: "cli", pomodorosPerCycle: 1, workMinutes: 1, longBreakMinutes: 2 })
  const sim = newSim(cfg)
  startFor(sim, "3", "Wire it")
  sim.tick(60)
  assert.equal(sim.state.phase, "longBreak")
  sim.clear()
  assert.equal(sim.apply({ type: "reset" }), "reset")
  assert.equal(sim.records().length, 0)
  assertIdleAfterReset(sim, 1)
  const sim2 = newSim(cfg)
  sim2.apply({ type: "toggle" })
  sim2.tick(60)
  sim2.apply({ type: "pause" })
  sim2.clear()
  assert.equal(sim2.apply({ type: "reset" }), "reset")
  assert.equal(sim2.records().length, 0)
  assertIdleAfterReset(sim2, 1)
})

test("reset with backend none never records; the record error and a pending close survive a reset", () => {
  const sim = newSim(T.settings({}))
  startFor(sim, "3", "Wire it")
  sim.tick(20)
  sim.clear()
  assert.equal(sim.apply({ type: "reset" }), "reset")
  assert.equal(sim.records().length, 0)
  assertIdleAfterReset(sim, 0)
  const sim2 = newSim(CLI)
  startFor(sim2, "3", "Wire it")
  sim2.tick(10)
  sim2.answer = () => ({ exitCode: 75 })
  sim2.clear()
  assert.equal(sim2.apply({ type: "reset" }), "reset")
  assert.equal(sim2.state.lastRecordError, "database busy")
  assert.equal(sim2.state.pendingClose.verb, "cancel")
  assert.equal(sim2.state.pendingClose.focusSeconds, 10)
  assertIdleAfterReset(sim2, 0)
  // The failed reply's write (the harness answers before the reset's own
  // write is collected) carries the pending close in an idle document.
  const kept = sim2.writes().find((w) => w.doc.pendingClose !== null)
  assert.equal(kept.doc.phase, "idle")
  assert.equal(kept.doc.pendingClose.verb, "cancel")
})

test("detach during a break clears the label without a record and without focus time", () => {
  const sim = newSim(CLI)
  startFor(sim, "3", "Wire…")
  sim.tick(1500)
  sim.clear()
  sim.now += 1500
  assert.equal(sim.apply({ type: "detach" }), "detached")
  assert.equal(sim.records().length, 0)
  assert.equal(sim.state.taskLabel, "")
  assert.equal(sim.state.focusSeconds, 0)
  assert.equal(sim.state.running, true)
})

// ---------------------------------------- ticks, focus time and the cycle

// 1500 s of work around a 600 s pause completes at AC-6.12's 2100 s.
test("AC-6.12 pauses are excluded from focus seconds", () => {
  const sim = newSim(CLI)
  startFor(sim, "3", "Wire…")
  sim.tick(600)
  sim.apply({ type: "pause" })
  sim.tick(600)
  assert.equal(sim.state.phase, "work")
  assert.equal(sim.state.remaining, 900)
  sim.apply({ type: "resume" })
  sim.tick(900)
  assert.equal(sim.now, 2100000)
  assert.equal(sim.state.phase, "shortBreak")
  assert.equal(sim.records().find((e) => e.verb === "done").focusSeconds, 1500)
})

test("AC-6.15 suspend pauses; it never completes", () => {
  const sim = newSim(CLI)
  startFor(sim, "3", "Wire…")
  sim.tick(300)
  assert.equal(sim.state.remaining, 1200)
  sim.clear()
  sim.now = 3900000
  sim.apply({ type: "tick" })
  assert.equal(sim.state.running, false)
  assert.equal(sim.state.phase, "work")
  assert.equal(Math.abs(sim.state.remaining - 1200) <= 1, true)
  assert.equal(sim.state.focusSeconds, 300)
  assert.equal(sim.records().length, 0)
  assert.equal(sim.writes().length, 1)
  assert.equal(sim.state.endsAt, null)
  sim.apply({ type: "resume" })
  sim.tick(1200)
  assert.equal(sim.state.phase, "shortBreak")
  assert.equal(sim.records().find((e) => e.verb === "done").focusSeconds, 1500)
})

test("AC-6.18 the state file is checkpointed at most once a minute while running", () => {
  const sim = newSim(CLI)
  startFor(sim, "3", "Wire…")
  sim.clear()
  sim.tick(150)
  const w = sim.writes()
  assert.deepEqual(w.map((e) => e.doc.updatedAt), [60000, 120000])
  assert.deepEqual(w.map((e) => e.doc.focusSeconds), [60, 120])
  sim.clear()
  sim.apply({ type: "pause" })
  assert.equal(sim.writes().length, 1)
  assert.equal(sim.writes()[0].doc.focusSeconds, 150)
  assert.equal(sim.writes()[0].doc.running, false)
  sim.clear()
  sim.tick(200)
  assert.equal(sim.writes().length, 0)
})

test("tick while idle or paused changes nothing", () => {
  const sim = newSim(CLI)
  sim.tick(5)
  assert.equal(sim.state.phase, "idle")
  assert.equal(sim.effects.length, 0)
  startFor(sim, "3", "Wire…")
  sim.apply({ type: "pause" })
  sim.clear()
  sim.tick(5)
  assert.equal(sim.effects.length, 0)
  assert.equal(sim.state.focusSeconds, 0)
})

test("focus seconds add min(2, Δt) per tick; break time is not focus time", () => {
  const sim = newSim(CLI)
  startFor(sim, "3", "Wire…")
  sim.now += 4000
  sim.apply({ type: "tick" })
  assert.equal(sim.state.focusSeconds, 2)
  assert.equal(sim.state.remaining, 1496)
  sim.now += 1500
  sim.apply({ type: "tick" })
  assert.equal(sim.state.focusSeconds, 3.5)
  sim.apply({ type: "skip" })
  assert.equal(sim.records().at(-1).focusSeconds, 4)
  sim.tick(10)
  assert.equal(sim.state.focusSeconds, 0)
})

test("long break after pomodorosPerCycle; the count resets after it", () => {
  const sim = newSim(T.settings({ backend: "cli", pomodorosPerCycle: 2, workMinutes: 1, shortBreakMinutes: 1, longBreakMinutes: 2 }))
  sim.apply({ type: "toggle" })
  sim.tick(60)
  assert.equal(sim.state.phase, "shortBreak")
  assert.equal(sim.state.completed, 1)
  sim.tick(60)
  assert.equal(sim.state.phase, "work")
  assert.equal(sim.state.running, false)
  sim.apply({ type: "toggle" })
  sim.tick(60)
  assert.equal(sim.state.phase, "longBreak")
  assert.equal(sim.state.completed, 2)
  assert.equal(sim.state.remaining, 120)
  assert.equal(sim.notifies().at(-1).argv[6], "Long break — you earned it.")
  sim.tick(120)
  assert.equal(sim.state.phase, "work")
  assert.equal(sim.state.completed, 0)
})

test("sound effects are omitted when sound is off", () => {
  const sim = newSim(T.settings({ sound: "false", workMinutes: 1 }))
  sim.apply({ type: "toggle" })
  sim.tick(60)
  assert.equal(sim.notifies().length, 1)
  assert.equal(sim.sounds().length, 0)
})

test("unknown events are ignored, including prototype keys and a missing event", () => {
  const sim = newSim(CLI)
  assert.equal(sim.apply({ type: "bogus" }), "")
  assert.equal(sim.apply({}), "")
  assert.equal(sim.apply({ type: "toString" }), "")
  assert.equal(sim.apply({ type: "hasOwnProperty" }), "")
  assert.equal(sim.apply(null), "")
  assert.equal(sim.apply(undefined), "")
  assert.equal(sim.effects.length, 0)
  sim.apply({ type: "recordResult", id: 99, exitCode: 0, exitStatus: 0, stdout: "", stderr: "" })
  assert.equal(sim.state.lastRecordError, null)
})
