// What the widgets and `status` show (UX §5.1, §5.2; PLAN §7.4, A53): the
// status JSON shape with a live `remaining`, the view the pill and the popup
// bind to, the tooltip and hint copy, the captions and the pill geometry.
// States come from the machine driven through Timer.js.
import { test } from "node:test"
import assert from "node:assert/strict"
import { loadQmlJs } from "./qml-js-loader.mjs"
import { Sim, fakeSessions, startFor } from "./harness.mjs"

const T = loadQmlJs(new URL("../Timer.js", import.meta.url).pathname)
const CLI = T.settings({ backend: "cli" })
const NONE = T.settings({})
const fake = fakeSessions()
const newSim = (cfg, now) => new Sim(T, cfg, { now, answer: fake.ok })

test("statusJson has the §7.4 shape; remaining is live while running", () => {
  const sim = newSim(CLI)
  startFor(sim, "3", "Wire it")
  sim.tick(10)
  const s = JSON.parse(T.statusJson(sim.state, CLI, sim.now + 2500))
  assert.deepEqual(Object.keys(s), ["version", "backend", "cliPath", "phase", "running", "remaining", "endsAt", "completed", "taskId", "label", "sessionUid", "lastRecordError", "restored"])
  assert.equal(s.version, 1)
  assert.equal(s.backend, "cli")
  assert.equal(s.cliPath, "todocli")
  assert.equal(s.phase, "work")
  assert.equal(s.running, true)
  assert.equal(s.remaining, 1488)
  assert.equal(s.endsAt, 1500000)
  assert.equal(s.taskId, "3")
  assert.equal(s.label, "Wire it")
  assert.equal(s.sessionUid, fake.last)
  assert.equal(s.lastRecordError, null)
  assert.equal(s.restored, false)
  sim.apply({ type: "pause" })
  assert.equal(JSON.parse(T.statusJson(sim.state, CLI, sim.now + 99000)).remaining, 1490)
  assert.equal(JSON.parse(T.statusJson(T.initialState(), NONE)).remaining, 0)
})

test("view and tooltip per UX 5.1; hint per 5.2", () => {
  const sim = newSim(CLI)
  let v = T.view(sim.state, CLI)
  assert.equal(v.tooltip, "Pomodoro — click to start")
  assert.equal(v.phaseLabel, "Pomodoro")
  assert.equal(v.phaseGlyph, "\uf2f2")
  assert.equal(v.hasSession, false)
  assert.equal(v.playing, false)
  assert.equal(v.timeText, "25:00")
  assert.equal(v.remainingText, "0:00")
  assert.equal(v.progress, 1) // upstream: remainingSeconds 0 at idle fills the bar
  assert.equal(v.hint, "Space start · R reset · S skip")
  assert.equal(v.attached, false)
  startFor(sim, "3", "Write UX spec for the panels")
  sim.tick(378)
  v = T.view(sim.state, CLI)
  assert.equal(v.tooltip, "Work — 18:42\nWrite UX spec for the panels")
  assert.equal(v.hint, "Space start · R reset · S skip · X detach")
  assert.equal(v.attached, true)
  assert.equal(v.playing, true)
  assert.equal(v.isBreak, false)
  assert.equal(Math.round(v.progress * 1000), 252)
  assert.equal(v.timeText, "18:42")
  sim.apply({ type: "pause" })
  v = T.view(sim.state, CLI)
  assert.equal(v.tooltip, "Work — paused\nWrite UX spec for the panels")
  assert.equal(v.playing, false)
  sim.apply({ type: "resume" })
  sim.tick(1122)
  sim.tick(110)
  v = T.view(sim.state, CLI)
  assert.equal(v.tooltip, "Short break — 3:10\nNext: Write UX spec for the panels")
  assert.equal(v.isBreak, true)
  assert.equal(v.phaseGlyph, "󰅶")
  assert.equal(v.phaseLabel, "Short break")
  assert.equal(v.completed, 1)
  assert.equal(v.perCycle, 4)
  sim.apply({ type: "pause" })
  assert.equal(T.view(sim.state, CLI).tooltip, "Short break — paused\nNext: Write UX spec for the panels")
  sim.apply({ type: "detach" })
  assert.equal(T.view(sim.state, CLI).tooltip, "Short break — paused")
  assert.equal(T.view(sim.state, CLI).hint, "Space start · R reset · S skip")
  startFor(sim, "5", "<img src=x> <b>x</b>")
  assert.equal(T.view(sim.state, CLI).tooltip, "Work — 25:00\n‹img src=x› ‹b›x‹/b›")
  assert.equal(T.view(sim.state, CLI).taskLabel, "<img src=x> <b>x</b>")
  assert.equal(T.tooltipText("a<b>c"), "a‹b›c")
  const s2 = newSim(T.settings({ pomodorosPerCycle: 2, workMinutes: 1, shortBreakMinutes: 1, longBreakMinutes: 3 }))
  s2.apply({ type: "toggle" }); s2.tick(60); s2.tick(60); s2.apply({ type: "toggle" }); s2.tick(60)
  const lv = T.view(s2.state, s2.cfg)
  assert.equal(lv.phaseLabel, "Long break")
  assert.equal(lv.timeText, "3:00")
  assert.equal(lv.tooltip, "Long break — 3:00")
  assert.equal(T.view(Object.assign(T.initialState(), { phase: "work", remaining: 0 }), T.settings({ workMinutes: "x" })).progress, 1)
  assert.equal(T.view(Object.assign(T.initialState(), { phase: "work", remaining: 10 }), T.settings({})).progress, 1 - 10 / 1500)
})

test("pillLayout: horizontal keeps upstream size and dims idle; vertical is barSize × iconSlot, glyph only, dims unless playing", () => {
  const m = { barSize: 26, iconSlot: 27, pillWidth: 56 }
  const idle = T.idleView()
  const paused = Object.assign({}, idle, { hasSession: true, playing: false })
  const playing = Object.assign({}, idle, { hasSession: true, playing: true })
  assert.deepEqual(T.pillLayout(false, m, idle), { width: 56, height: 26, showTime: true, opacity: 0.7 })
  assert.deepEqual(T.pillLayout(false, m, paused), { width: 56, height: 26, showTime: true, opacity: 1.0 })
  assert.deepEqual(T.pillLayout(false, m, playing), { width: 56, height: 26, showTime: true, opacity: 1.0 })
  assert.deepEqual(T.pillLayout(true, { barSize: 28, iconSlot: 27, pillWidth: 56 }, paused), { width: 28, height: 27, showTime: false, opacity: 0.7 })
  assert.deepEqual(T.pillLayout(true, { barSize: 28, iconSlot: 27, pillWidth: 56 }, playing), { width: 28, height: 27, showTime: false, opacity: 1.0 })
})

test("view exposes exactly what the pill and the popup bind; idleView is the widgets' fallback", () => {
  const keys = ["isBreak", "hasSession", "playing", "phaseGlyph", "phaseLabel", "progress", "timeText", "remainingText", "tooltip", "hint", "attached", "taskLabel", "completed", "perCycle", "recordCaption", "restored", "restoredCaption"]
  assert.deepEqual(Object.keys(T.view(T.initialState(), NONE)).sort(), keys.slice().sort())
  assert.deepEqual(T.idleView(), T.view(T.initialState(), T.settings({})))
  assert.equal(T.idleView().tooltip, "Pomodoro — click to start")
})

test("captions: record error and restored copy (UX 5.2)", () => {
  assert.equal(T.recordCaption(null), "")
  assert.equal(T.recordCaption("database busy"), "Last session not recorded: database busy.")
  assert.equal(T.restoredCaption(true), "Restored after a reload · Space resumes")
  assert.equal(T.restoredCaption(false), "")
  const sim = newSim(CLI, 1000000 + 40000)
  sim.restore({ version: 1, phase: "work", running: false, remaining: 100, completed: 0, taskId: "", taskLabel: "", sessionUid: null, focusSeconds: 0, pendingClose: null, updatedAt: 1000000 })
  assert.equal(T.view(sim.state, CLI).restoredCaption, "Restored after a reload · Space resumes")
  sim.answer = () => ({ exitCode: 75 })
  sim.apply({ type: "resume" })
  assert.equal(T.view(sim.state, CLI).recordCaption, "Last session not recorded: database busy.")
  assert.equal(T.view(sim.state, CLI).restoredCaption, "")
})
